name: lin-alg
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.0=py37_0
  - asn1crypto=1.3.0=py37_0
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py37_0
  - blas=1.0=mkl
  - ca-certificates=2020.1.1=0
  - certifi=2020.4.5.1=py37_0
  - cffi=1.14.0=py37hb5b8e2f_0
  - chardet=3.0.4=py37_1003
  - cloudpickle=1.3.0=py_0
  - conda=4.8.3=py37_0
  - conda-package-handling=1.6.0=py37h1de35cc_0
  - cryptography=2.8=py37ha12b0ac_0
  - cycler=0.10.0=py37_0
  - cytoolz=0.10.1=py37h1de35cc_0
  - dask-core=2.14.0=py_0
  - dbus=1.13.12=h90a0687_0
  - decorator=4.4.2=py_0
  - expat=2.2.6=h0a44026_0
  - freetype=2.9.1=hb4e5f40_0
  - gettext=0.19.8.1=h15daf44_3
  - glib=2.63.1=hd977a24_0
  - icu=58.2=h4b95b61_1
  - idna=2.9=py_1
  - imageio=2.8.0=py_0
  - importlib_metadata=1.5.0=py37_0
  - intel-openmp=2019.4=233
  - ipykernel=5.1.4=py37h39e3cac_0
  - ipympl=0.5.6=pyh9f0ad1d_1
  - ipython=7.13.0=py37h5ca1d4c_0
  - ipython_genutils=0.2.0=py37_0
  - ipywidgets=7.5.1=py_0
  - jedi=0.16.0=py37_1
  - jinja2=2.11.1=py_0
  - joblib=0.14.1=py_0
  - jpeg=9b=he5867d9_2
  - jsonschema=3.2.0=py37_0
  - jupyter=1.0.0=py37_7
  - jupyter_client=6.1.2=py_0
  - jupyter_console=6.1.0=py_0
  - jupyter_core=4.6.3=py37_0
  - kiwisolver=1.1.0=py37h0a44026_0
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=h93005f0_2
  - libiconv=1.15=hdd342a3_7
  - libpng=1.6.37=ha441bb4_0
  - libsodium=1.0.16=h3efe00b_0
  - libtiff=4.1.0=hcb84e12_0
  - llvm-openmp=4.0.1=hcfea43d_1
  - markupsafe=1.1.1=py37h1de35cc_0
  - matplotlib=3.1.1=py37_1
  - matplotlib-base=3.1.1=py37h3a684a6_1
  - mistune=0.8.4=py37h1de35cc_0
  - mkl=2019.4=233
  - mkl-service=2.3.0=py37hfbe908c_0
  - mkl_fft=1.0.15=py37h5e564d8_0
  - mkl_random=1.1.0=py37ha771720_0
  - nbconvert=5.6.1=py37_0
  - ncurses=6.2=h0a44026_0
  - networkx=2.4=py_0
  - ninja=1.9.0=py37h04f5b5a_0
  - notebook=6.0.3=py37_0
  - numpy=1.18.1=py37h7241aed_0
  - numpy-base=1.18.1=py37h6575580_1
  - olefile=0.46=py37_0
  - openssl=1.1.1f=h1de35cc_0
  - pandas=0.25.3=py37h0a44026_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py37_1
  - parso=0.6.2=py_0
  - pcre=8.43=h0a44026_0
  - pexpect=4.8.0=py37_0
  - pickleshare=0.7.5=py37_0
  - pillow=7.0.0=py37h4655f20_0
  - pip=20.0.2=py37_1
  - plotly=4.6.0=py_0
  - prometheus_client=0.7.1=py_0
  - prompt-toolkit=3.0.4=py_0
  - prompt_toolkit=3.0.4=0
  - ptyprocess=0.6.0=py37_0
  - pycosat=0.6.3=py37h1de35cc_0
  - pycparser=2.20=py_0
  - pygments=2.6.1=py_0
  - pyopenssl=19.1.0=py37_0
  - pyparsing=2.4.6=py_0
  - pyqt=5.9.2=py37h655552a_2
  - pysocks=1.7.1=py37_0
  - python=3.7.6=h359304d_1
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pytorch=1.4.0=py3.7_0
  - pytz=2019.3=py_0
  - pywavelets=1.1.1=py37h1de35cc_0
  - pyzmq=18.1.1=py37h0a44026_0
  - qt=5.9.7=h468cd18_1
  - qtconsole=4.7.2=py_0
  - qtpy=1.9.0=py_0
  - readline=7.0=h1de35cc_5
  - requests=2.23.0=py37_0
  - retrying=1.3.3=py37_2
  - ruamel_yaml=0.15.87=py37h1de35cc_0
  - scikit-image=0.15.0=py37h0a44026_0
  - scikit-learn=0.22.1=py37h27c97d8_0
  - scipy=1.4.1=py37h9fa6033_0
  - send2trash=1.5.0=py37_0
  - setuptools=46.1.3=py37_0
  - sip=4.19.8=py37h0a44026_0
  - six=1.14.0=py37_0
  - sqlite=3.31.1=ha441bb4_0
  - terminado=0.8.3=py37_0
  - testpath=0.4.4=py_0
  - tk=8.6.8=ha441bb4_0
  - toolz=0.10.0=py_0
  - torchvision=0.5.0=py37_cpu
  - tornado=6.0.4=py37h1de35cc_1
  - tqdm=4.44.1=py_0
  - traitlets=4.3.3=py37_0
  - urllib3=1.25.8=py37_0
  - wcwidth=0.1.9=py_0
  - wheel=0.34.2=py37_0
  - widgetsnbextension=3.5.1=py37_0
  - xz=5.2.4=h1de35cc_4
  - yaml=0.1.7=hc338f04_2
  - zeromq=4.3.1=h0a44026_3
  - zipp=2.2.0=py_0
  - zlib=1.2.11=h1de35cc_3
  - zstd=1.3.7=h5bba6e5_0
  - pip:
    - bleach==3.1.0
    - defusedxml==0.6.0
    - entrypoints==0.3
    - fastscript==0.1.4
    - ipython-genutils==0.2.0
    - nbdev==0.2.5
    - nbformat==5.0.3
    - packaging==20.0
    - pyrsistent==0.15.7
    - pyyaml==5.3
    - webencodings==0.5.1
prefix: /Users/akash/anaconda3/envs/lin-alg

